### ISSUE TITLE
registry-mirror: docker-options.conf is invalid

### ISSUE THREAD

**Issue by michaelfuckner** [NVIDIA/deepops#809] opened 2020-12-25 08:41 UTC
When setting up a default config, the option registry-mirror in docker-options.conf is invalid, preventing docker from starting

 cat /etc/systemd/system/docker.service.d/docker-options.conf
[Service]
Environment="DOCKER_OPTS= --iptables=True \
--exec-opt native.cgroupdriver=systemd \
--insecure-registry=login01:5000:5000 --insecure-registry=registry.local:31500  \
--registry-mirror=http://login01:5000http://:5000  \
--data-root=/var/lib/docker \
--log-opt max-size=50m --log-opt max-file=5 \
"

**Comment by ajdecon** [comment] 2020-12-29 20:31
Unfortunately, I'm not able to duplicate this locally. When I run a default configuration on a new virtual development cluster, I get this:

```
vagrant@virtual-gpu01:~$ cat /etc/systemd/system/docker.service.d/docker-options.conf
[Service]
Environment="DOCKER_OPTS= --iptables=True \
--exec-opt native.cgroupdriver=systemd \
--insecure-registry=virtual-login01:5000 --insecure-registry=registry.local:31500  \
--registry-mirror=http://virtual-login01:5000  \
--data-root=/var/lib/docker \
--log-opt max-size=50m --log-opt max-file=5 \
"
```

The configuration for registry-mirror and insecure-registry are generated by default using the list of machines in the `slurm-master` group, i.e.

```
docker_insecure_registries: "{{ groups['slurm-master'] | map('regex_replace', '(.*)', '\\1:5000') | list + ['registry.local:31500'] }}"
docker_registry_mirrors: "{{ groups['slurm-master'] | map('regex_replace', '(.*)', 'http://\\1:5000') | list }}"
```

It looks like somehow an extra "empty" host is being included when these are being generated. I'm not sure how that could happen with an Ansible inventory 😄 but it might be worth checking your inventory to see if it includes any unexpected entries for that group.

If you still see issues, feel free to post your inventory file and I can try to help debug. You can also likely work around this by overriding the `docker_insecure_registries` and `docker_registry_mirrors` variables directly.

**Comment by michaelfuckner** [comment] 2020-12-30 08:32
I just did a very basic installation: DGX A100 (DGX OS 5) with login Server (login01, Ubuntu 20.04 LTS default installation). Doesn't even look like a CR-LF vs CR issue. Is my setup correct or is there any advice to use a DGX with multiple users?


Here is what I set up
/etc/hosts
192.168.1.1: login01
192.168.1.2  gpu01

config/group_vars/slurm-cluster.yml 
dns_mode: none 

A100 network access via NAT on login01
iptables -t nat -A POSTROUTING -o enp2s0f0 -j MASQUERADE 

user admin2
usermod -aG docker admin2
ssh-keys for passwordless login, /home login01 -> gpu01 via NFS

Installation Deepops
git clone https://github.com/NVIDIA/deepops.git
cd deepops
git submodule update --init --recursive
./scripts/setup.sh

edit config/inventory:
[all]
login01      ansible_host=192.168.1.1
gpu01        ansible_host=192.168.1.2

[slurm-master]
frontend

[slurm-node]
gpu01


Installation:

ansible all -m raw -a "hostname"
ansible-playbook -K -l slurm-cluster playbooks/slurm-cluster.yml
Reboot von frontend und dgxa100

**Comment by mathrock74** [comment] 2020-12-30 13:58
I'm seeing the exact same problem when trying to setup a test environment with vGPU VMs instead of DGX A100. OS is Ubuntu 20.04.1. I looked at my inventory file, I couldn't find anything unusual. I could only solve it by overriding the variables in submodules/kubespray/extra_playbooks/roles/container-engine/docker/templates/docker-options.conf.j2

ansible version on provisioning host:
ansible 2.9.5
  config file = /home/ubuntu/deepops-20.12/ansible.cfg
  configured module search path = ['/home/ubuntu/deepops-20.12/submodules/kubespray/library']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

**Comment by ajdecon** [comment] 2020-12-30 15:21
OK, this is good to know. I still can't reproduce on my end, but I'll investigate some more and try to understand what's going on.

One thing that would be useful to know is how Ansible is interpreting the group membership in the inventory. Could each of you try running the following command, and share the output?

```
$ ansible localhost -m debug -a 'var=groups'
```

@michaelfuckner : Your inventory file seems to have inconsistent naming, with both `login01` and `frontend` names being used for what I assume is the same machine?

```
[all]
login01 ansible_host=192.168.1.1
gpu01 ansible_host=192.168.1.2

[slurm-master]
frontend

[slurm-node]
gpu01
```

I assume you have some host alias going on here so that Ansible still runs, but it could be helpful to make sure the same names are in use everywhere for the same machine. This might help ensure Ansible isn't interpreting the inventory file incorrectly.

**Comment by mathrock74** [comment] 2020-12-30 15:34
ok: [localhost] => 
  groups:
    all:
    - deepops-login2
    - deepops-node3
    - deepops-node4
    etcd: []
    k8s-cluster: []
    kube-master: []
    kube-node: []
    slurm-cluster:
    - deepops-login2
    - deepops-node3
    - deepops-node4
    slurm-master:
    - deepops-login2
    slurm-node:
    - deepops-node3
    - deepops-node4
    ungrouped: []

**Comment by michaelfuckner** [comment] 2020-12-30 15:53
it is login01. It was frontend on my first try to install?
Is this not the default way to use DGX with multiple users and persistent storage? Didn't anyone try this?

Another thing I saw: firewall and dgx pod use port 30200 for Grafana, slurm recipe 3000. Same for prometheus. Wouldn't it make sense to align the ports for all playbooks?

**Comment by ajdecon** [comment] 2020-12-30 16:11
> it is login01. It was frontend on my first try to install?

Got it. If you're re-running Ansible, it's a good idea to try to make sure the names are always consistent. I don't *think* this is the source of the problem, but it would be good to fix so we can validate it's not involved.

> Is this not the default way to use DGX with multiple users and persistent storage? Didn't anyone try this?

This is definitely something we've tried, it's just not an issue we've reproduced ourselves (yet!). On the development system I'm using, this works correctly. 

I'm spending some time on trying to debug this issue today. If I can reproduce the error I will try to fix it; if I can't reproduce, I'll discuss with the team and we may disable this by default while we debug further.

As a work-around, I'd recommend overriding the two variables involved in your `config/group_vars/slurm-cluster.yml` file:

```
docker_insecure_registries:
- "login01:5000"

docker_registry_mirrors:
- "http://login01:5000"
```

And then re-run the `ansible-playbook` command you used to set up the cluster.  This should hopefully solve the issue with auto-generating these values.

> Another thing I saw: firewall and dgx pod use port 30200 for Grafana, slurm recipe 3000. Same for prometheus. Wouldn't it make sense to align the ports for all playbooks?

Making these consistent is probably a good idea! If possible, I'd ask that you open a separate issue for this, so that we can keep this one focused on the registry-mirror issue.

**Comment by michaelfuckner** [comment] 2020-12-30 19:39
So your setup is also a physical machine with Ubuntu 20.04 LTS as login and slurm server? Would it help if I give you access to my lab setup next week?

**Comment by ajdecon** [comment] 2020-12-30 20:21
I've tested on Ubuntu 20.04 LTS and it looks ok. I'm working on getting a closer match to your test setup to validate.

> Would it help if I give you access to my lab setup next week?

Unfortunately, I don't think we can really do that level of support via Github issues. As you're running on a DGX A100, you should have access to NVIDIA Enterprise Support. If you raise this issue via NVES, that team should be able to do more direct support for your system.

**Comment by michaelfuckner** [comment] 2020-12-30 21:32
Nves denied Support since it is neither a hardware issue nor related to DGX OS.

Perhaps my setup is incorrect, but I believe DGX is just a Compute Node and can not be used standalone. So there must be a guide to combine DGX with a controller, Slurm via deepops and perhaps deeplearningexamples straight forward to something running out of the Box. It is now two months and the customer has nothing to work with yet

**Comment by ajdecon** [comment] 2020-12-30 22:08
@michaelfuckner :

I have tested on a couple of different test rigs on Ubuntu 20.04 with our default config, but I haven't been able to repro this issue yet.

I do suspect there's a DeepOps bug here! But it's clearly not straightforward to repro, and we haven't isolated the specific difference causing the issue yet.

I do recommend trying the work-around I posted earlier to try to get past the specific error. I'd also recommend running ansible-playbook with the '--flush-cache' flag just in case some obsolete data was cached and is causing some issue.

If you're willing, I'd also be happy to take this to email (adeconinck@nvidia.com) to make sure the right folks on our end are in the loop. This will definitely be helpful if we want to try to arrange a remote login at some point -- that's really not something we should do over Github!

**Comment by andiariffin** [comment] 2021-01-04 21:42
got the same issue here, my `docker-options.conf` value ended up like this:

```
[Service]
Environment="DOCKER_OPTS= --iptables=True \
--exec-opt native.cgroupdriver=systemd \
--insecure-registry=mgmt01:5000:5000 --insecure-registry=registry.local:31500  \
--registry-mirror=http://mgmt01:5000http://:5000  \
--data-root=/var/lib/docker \
--log-opt max-size=50m --log-opt max-file=5 \
"
```

according to this:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#searching-strings-with-regular-expressions

replacing `'(.*)'` to `'^(.*)$'` solve the issue for me: 

```
docker_insecure_registries: "{{ groups['kube-master']|map('regex_replace', '^(.*)$', '\\1:5000')|list + ['registry.local:31500']}}"
docker_registry_mirrors: "{{ groups['kube-master'] | map('regex_replace', '^(.*)$', 'http://\\1:5000') | list }}"
```

**Comment by michaelfuckner** [comment] 2021-01-06 07:12
'^(.*)$' generates a correct docker-options.conf for mee, too! Please commit!

**Comment by ajdecon** [comment] 2021-01-06 16:01
Thanks @andiariffin for solving the issue and getting a PR in! PR is merged, closing this issue.

**Closed by ajdecon** 2021-01-06 16:01 UTC
