### ISSUE TITLE
msg: No package matching 'python2-openshift' found available, installed or updated

### ISSUE THREAD

**Issue by k8s-junkie** [NVIDIA/deepops#393] opened 2019-12-12 22:18 UTC
Getting this error when trying to create a k8s-cluster on centos nodes..

PLAY [kube-master] **************************************************************************************************************************************************************************
META: ran handlers

TASK [install k8s GPU plugin] ***************************************************************************************************************************************************************
task path: /home/centos/cr8-mec-deployment/cr8-k8s-cluster/playbooks/k8s-gpu-plugin.yml:7

TASK [k8s-gpu-plugin : install virtualenv] **************************************************************************************************************************************************
task path: /home/centos/cr8-mec-deployment/cr8-k8s-cluster/roles/k8s-gpu-plugin/tasks/main.yml:2
skipping: [cpu-node0] => (item=[])  => changed=false 
  ansible_loop_var: item
  item: []
  skip_reason: Conditional result was False

TASK [k8s-gpu-plugin : create location for python virtual env] ******************************************************************************************************************************
task path: /home/centos/cr8-mec-deployment/cr8-k8s-cluster/roles/k8s-gpu-plugin/tasks/main.yml:11
skipping: [cpu-node0] => changed=false 
  skip_reason: Conditional result was False

TASK [k8s-gpu-plugin : install openshift python client for k8s_raw module] ******************************************************************************************************************
task path: /home/centos/cr8-mec-deployment/cr8-k8s-cluster/roles/k8s-gpu-plugin/tasks/main.yml:17
skipping: [cpu-node0] => changed=false 
  skip_reason: Conditional result was False

TASK [k8s-gpu-plugin : install openshift python client for k8s_raw module] ******************************************************************************************************************
task path: /home/centos/cr8-mec-deployment/cr8-k8s-cluster/roles/k8s-gpu-plugin/tasks/main.yml:23
Using module file /usr/lib/python2.7/site-packages/ansible/modules/packaging/os/yum.py
Pipelining is enabled.
<192.168.1.141> ESTABLISH SSH CONNECTION FOR USER: centos
<192.168.1.141> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="centos"' -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' 192.168.1.141 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-jkhagfnslfgdjqvplfmvfarrnhilwzsm ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<192.168.1.141> (1, '\n{"changed": false, "results": ["No package matching \'python2-openshift\' found available, installed or updated"], "failed": true, "rc": 126, "invocation": {"module_args": {"lock_timeout": 30, "update_cache": false, "disable_excludes": null, "exclude": [], "allow_downgrade": false, "disable_gpg_check": false, "conf_file": null, "use_backend": "auto", "state": null, "disablerepo": [], "releasever": null, "skip_broken": false, "autoremove": false, "download_dir": null, "enable_plugin": [], "installroot": "/", "install_weak_deps": true, "name": ["python2-openshift"], "download_only": false, "bugfix": false, "list": null, "install_repoquery": true, "update_only": false, "disable_plugin": [], "enablerepo": [], "security": false, "validate_certs": true}}, "msg": "No package matching \'python2-openshift\' found available, installed or updated"}\n', '')
<192.168.1.141> Failed to connect to the host via ssh: 
fatal: [cpu-node0]: FAILED! => changed=false 
  invocation:
    module_args:
      allow_downgrade: false
      autoremove: false
      bugfix: false
      conf_file: null
      disable_excludes: null
      disable_gpg_check: false
      disable_plugin: []
      disablerepo: []
      download_dir: null
      download_only: false
      enable_plugin: []
      enablerepo: []
      exclude: []
      install_repoquery: true
      install_weak_deps: true
      installroot: /
      list: null
      lock_timeout: 30
      name:
      - python2-openshift
      releasever: null
      security: false
      skip_broken: false
      state: null
      update_cache: false
      update_only: false
      use_backend: auto
      validate_certs: true
  msg: No package matching 'python2-openshift' found available, installed or updated
  rc: 126
  results:
  - No package matching 'python2-openshift' found available, installed or updated

PLAY RECAP **********************************************************************************************************************************************************************************
cpu-node0                  : ok=407  changed=40   unreachable=0    failed=1    skipped=630  rescued=0    ignored=0   
cpu-node1                  : ok=280  changed=19   unreachable=0    failed=0    skipped=305  rescued=0    ignored=0   
gpu-node0                  : ok=287  changed=24   unreachable=0    failed=0    skipped=306  rescued=0    ignored=0   
gpu-node1                  : ok=287  changed=24   unreachable=0    failed=0    skipped=306  rescued=0    ignored=0   

[centos@centos-infra-vm cr8-k8s-cluster]$ sudo pip install python2-openshift
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement python2-openshift (from versions: none)
ERROR: No matching distribution found for python2-openshift

Output on cpu-node0(192.168.1.141)
[centos@cpu-node0 ~]$ yum whatprovides python2-openshift
base/7/x86_64/filelists_db                                                                                                                           | 7.3 MB  00:00:00     
docker-ce/x86_64/filelists_db                                                                                                                        |  18 kB  00:00:00     
docker-engine/filelists_db                                                                                                                           |  40 kB  00:00:00     
extras/7/x86_64/filelists_db                                                                                                                         | 207 kB  00:00:00     
updates/7/x86_64/filelists_db                                                                                                                        | 3.3 MB  00:00:00     
No matches found

The actual yml that is trying to install plugin is
[centos@centos-infra-vm cr8-k8s-cluster]$ cat /home/centos/cr8-mec-deployment/cr8-k8s-cluster/roles/k8s-gpu-plugin/tasks/main.yml
---
- name: install virtualenv
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "virtualenv"
    - "python-setuptools"
  when: ansible_distribution == 'Ubuntu'

- name: create location for python virtual env
  file:
    path: "{{ deepops_dir }}"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  pip:
    name: openshift
    virtualenv: "{{ deepops_venv }}"
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  yum:
    name: python2-openshift
  when: ansible_os_family == 'RedHat'

- name: create GPU device plugin
  k8s:
    state: present
    definition: "{{ lookup('url', nvidia_k8s_device_plugin_def, split_lines=False) }}"
  run_once: true
  environment:
    PYTHONHOME: '{{ deepops_venv }}'
  when: ansible_distribution == 'Ubuntu'

- name: create GPU device plugin
  k8s:
    state: present
    definition: "{{ lookup('url', nvidia_k8s_device_plugin_def, split_lines=False) }}"
  run_once: true
  when: ansible_os_family == 'RedHat'

**Comment by supertetelman** [comment] 2019-12-12 23:06
This is related to the half-complete PR: https://github.com/NVIDIA/deepops/pull/227

I'm hoping to get to this and clean it up sometime soon, this debug helps, thanks.

**Comment by supertetelman** [comment] 2019-12-17 22:07
Can you give us some more information about the system you are running on?

I just provisioned a CentOS 7 cluster and see the following output:
```
[centos@deepops-mgmt3 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[centos@deepops-mgmt3 ~]$ yum whatprovides python2-openshift
1:python2-openshift-0.10.0-1.el7.noarch : Python client for the OpenShift API
Repo        : epel
``

**Comment by jaimehrubiks** [comment] 2019-12-30 18:15
Same error here:
`[root@nxt-k8s-master-1 ~]# yum whatprovides python2-openshift
base/7/x86_64/filelists_db                                                                                                                                                                                     | 7.3 MB  00:01:11
docker-ce/x86_64/filelists_db                                                                                                                                                                                  |  18 kB  00:00:00
docker-engine/filelists_db                                                                                                                                                                                     |  40 kB  00:00:00
extras/7/x86_64/filelists_db                                                                                                                                                                                   | 207 kB  00:00:01
updates/7/x86_64/filelists_db                                                                                                                                                                                  | 3.3 MB  00:00:20
No matches found
[root@nxt-k8s-master-1 ~]# cat cat /etc/os-release
cat: cat: No such file or directory
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`

**Comment by ajdecon** [comment] 2019-12-30 21:58
I can reproduce this issue on fresh CentOS VMs. The issue seems to be that `python2-openshift` is in [EPEL](https://centos.pkgs.org/7/epel-x86_64/python2-openshift-0.10.0-1.el7.noarch.rpm.html), but a default CentOS VM won't necessarily include this repo.

I'll open a PR to make sure EPEL is present before installing this package. In the mean time, installing the EPEL repository with `yum install epel-release` is a good workaround.

**Comment by jaimehrubiks** [comment] 2019-12-31 12:04
Yes, it seems that python2-openshift is now in EPEL, I used that workaround too.

**Comment by michael-balint** [comment] 2020-01-03 20:43
#227 should fix this and is merged into master

**Closed by michael-balint** 2020-01-03 20:43 UTC
