### ISSUE TITLE
Container registry fails to deploy

### ISSUE THREAD

**Issue by crd477** [NVIDIA/deepops#738] opened 2020-10-27 15:17 UTC
I tried to deploy an internal container registry with the following, as described in https://github.com/NVIDIA/deepops/blob/master/docs/deepops/dgx-pod.md#4-deploy-basic-cluster-services:
`ansible-playbook --tags container-registry playbooks/k8s-cluster/k8s-services.yml`

This failed with the following (`-vvv` output included):
```
[...]
TASK [Get tiller service info] ************************************************************************************************************************************************************************************************************************************************
task path: /home/ubuntu/deepops/playbooks/k8s-cluster/k8s-services.yml:33
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/clustering/k8s/_k8s_facts.py
Pipelining is enabled.
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: yyy
<1.2.3.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="yyy"' -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' 1.2.3.4 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ofqgfkcafdlzpoonknpwantjrszjzjre ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<1.2.3.4> (1, '\n{"msg": "Failed to import the required Python library (openshift) on xxx-mgmt\'s Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter", "failed": true, "exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_k8s_facts_payload_jqdSsj/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py\\", line 33, in <module>\\n    import kubernetes\\nImportError: No module named kubernetes\\n", "error": "No module named kubernetes", "invocation": {"module_args": {"username": null, "kind": "Service", "api_key": null, "field_selectors": [], "name": "tiller-deploy", "ca_cert": null, "namespace": "kube-system", "label_selectors": [], "kubeconfig": null, "host": null, "proxy": null, "context": null, "password": null, "validate_certs": null, "client_cert": null, "api_version": "v1", "client_key": null}}}\n', '')
<1.2.3.4> Failed to connect to the host via ssh:
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_k8s_facts_payload_jqdSsj/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py", line 33, in <module>
    import kubernetes
ImportError: No module named kubernetes
fatal: [xxx-mgmt]: FAILED! => changed=false
  error: No module named kubernetes
  invocation:
    module_args:
      api_key: null
      api_version: v1
      ca_cert: null
      client_cert: null
      client_key: null
      context: null
      field_selectors: []
      host: null
      kind: Service
      kubeconfig: null
      label_selectors: []
      name: tiller-deploy
      namespace: kube-system
      password: null
      proxy: null
      username: null
      validate_certs: null
  msg: Failed to import the required Python library (openshift) on xxx-mgmt's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
xxx-mgmt                : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```

I manually installed `python3-pip` on the mgmt node and retried the process using `--extra-vars ansible_python_interpreter=/usr/bin/python3` but that resulted in the same error.

**Comment by ajdecon** [comment] 2020-10-27 18:49
Confirmed this issue. Opened #739 to address it but still needs a little work.

**Comment by supertetelman** [comment] 2021-01-28 21:38
Looks like this is fixed.

I'd like to add some additional testing for this playbook before closing the issue.

**Closed** 2021-01-28 23:03 UTC
Labels: bug
